import { careerCatalog } from "../data/demo.js";

const base = [
  [
    "student",
    "ESTUDIANTE",
    "actor",
    -240,
    85,
    10,
    0,
    "Juan Pérez presenta una consulta de orientación.",
  ],
  [
    "inputs",
    "ENTRADAS",
    "input",
    -170,
    80,
    0,
    2,
    "Consulta, historial, BTH y respuestas RIASEC.",
  ],
  [
    "peter3",
    "PETER 3",
    "orchestrator",
    -85,
    100,
    0,
    3,
    "Orquestación de la ejecución demo.",
  ],
  [
    "riasec",
    "RIASEC",
    "processor",
    -50,
    25,
    -55,
    4,
    "Normaliza 30 reactivos y deriva el código Holland.",
  ],
  [
    "analytics",
    "ANALYTICS",
    "processor",
    0,
    95,
    65,
    4,
    "Calcula tendencias y último valor por asignatura.",
  ],
  [
    "retrieval",
    "RETRIEVAL",
    "knowledge",
    25,
    10,
    -25,
    4,
    "Búsqueda léxica en el corpus local demo.",
  ],
  [
    "evidence",
    "EVIDENCE ENGINE",
    "evidence",
    75,
    45,
    0,
    5,
    "Integra dimensiones; mantiene ausencias como null.",
  ],
  [
    "bridge",
    "BRIDGE V2",
    "bridge",
    150,
    35,
    0,
    6,
    "Ejecuta reglas de relación ocupacional.",
  ],
  [
    "careers",
    "PERFILES",
    "career",
    215,
    60,
    15,
    6,
    "Perfiles cualitativos de carrera.",
  ],
  [
    "simulation",
    "SIMULACIÓN",
    "simulation",
    210,
    -55,
    45,
    7,
    "Tres escenarios generan nueva evidencia.",
  ],
  [
    "tutor",
    "TUTOR",
    "service",
    80,
    -85,
    -65,
    9,
    "Explicación referenciada a evidencia.",
  ],
  [
    "peter2",
    "PETER 2",
    "integration",
    20,
    -150,
    0,
    10,
    "Paquete local preparado para integración.",
  ],
  [
    "output",
    "ORIENTACIÓN",
    "output",
    -90,
    -130,
    35,
    11,
    "Salida cualitativa explicable y trazable.",
  ],
];
const paths = [
  ["student", "inputs", 2],
  ["inputs", "peter3", 3],
  ["peter3", "riasec", 4],
  ["peter3", "analytics", 4],
  ["peter3", "retrieval", 4],
  ["riasec", "evidence", 5],
  ["analytics", "evidence", 5],
  ["retrieval", "evidence", 5],
  ["inputs", "evidence", 5],
  ["evidence", "bridge", 6],
  ["bridge", "careers", 6],
  ["careers", "simulation", 7],
  ["simulation", "evidence", 8],
  ["evidence", "tutor", 9],
  ["careers", "tutor", 9],
  ["tutor", "peter2", 10],
  ["peter2", "output", 11],
];

export function buildGraph() {
  const nodes = base.map(
    ([id, label, type, fx, fy, fz, phase, description]) => ({
      id,
      label,
      type,
      fx,
      fy,
      fz,
      phase,
      description,
    }),
  );
  careerCatalog.slice(0, 6).forEach((career, index) =>
    nodes.push({
      id: career.id,
      label: career.name,
      type: "career",
      fx: 290,
      fy: 142 - index * 33,
      fz: index % 2 ? 45 : -35,
      phase: 6,
      description: `${career.area}; ${career.occupations.join(", ")}`,
    }),
  );
  const links = paths.map(([source, target, phase]) => ({
    source,
    target,
    phase,
    id: `${source}:${target}`,
  }));
  careerCatalog.slice(0, 6).forEach((career) =>
    links.push({
      source: "careers",
      target: career.id,
      phase: 6,
      id: `careers:${career.id}`,
    }),
  );
  return { nodes, links };
}

export const colors = {
  actor: "#68d9f0",
  input: "#69c9ef",
  orchestrator: "#6fd7e8",
  processor: "#b99bf2",
  knowledge: "#e7bd7d",
  evidence: "#6cafff",
  bridge: "#70d7d2",
  career: "#e6a4d5",
  simulation: "#eba76d",
  service: "#bb9beb",
  integration: "#78b8ed",
  output: "#efce7e",
};
